services:
  postgres:
    image: 'postgres:15.5-alpine3.18'
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - 5000:8080
    tty: true
