spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/${POSTGRES_DB}?schema=bitsbids
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}