spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/${POSTGRES_DB}?schema=bitsbids
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  servlet:
    context-path: /api
    session:
      cookie:
        http-only: true
        path: /